# Generated by Django 3.1.2 on 2020-10-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0003_auto_20201005_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='child_id',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='person_id',
            new_name='person',
        ),
    ]
