# Generated by Django 3.1.2 on 2020-10-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0004_auto_20201010_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
